version: 2.1

orbs:
  ecr: pagerduty/ecr@1.0.0
  git: pagerduty/git@0.1.0        # https://circleci.com/orbs/registry/orb/pagerduty/git
  elixir: pagerduty/elixir@3.3.0  # https://circleci.com/orbs/registry/orb/pagerduty/elixir

working_dir: &working_dir
  working_directory: /tmp/workspace

base-image: &base-image
  image: cimg/base:stable-20.04

executors:
  elixir-dev-small:
    <<: *working_dir
    resource_class: small
    docker:
      - <<: *base-image
  elixir-dev-medium:
    <<: *working_dir
    resource_class: large
    docker:
      - <<: *base-image

setup_access_to_github: &setup_access_to_github
  run:
    name: Set up access to GitHub via SSH
    command: |
      ssh-add -D && echo "${GITHUB_SSH_KEY}" | base64 --decode | ssh-add -

commands:
  setup_service:
    steps:
      - <<: *setup_access_to_github
      - run:
          name: Update packages
          command: |
            sudo apt-get update
            sudo apt-get install -y libncurses5-dev
      - checkout
      - git/rebase_on_main
      - elixir/install:
          asdf_version: "v0.18.0"
      - elixir/mix_get_and_compile_deps

jobs:
  format:
    executor: elixir-dev-medium
    environment:
      MIX_ENV: dev
    steps:
      - setup_service
      - run: make format.check
  compiler_warnings:
    executor: elixir-dev-medium
    environment:
      MIX_ENV: dev
    steps:
      - setup_service
      - run: mix compile --force
  test:
    executor: elixir-dev-medium
    environment:
      MIX_ENV: test
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - setup_service
      - run: make coverage
      - store_test_results:
          path: pd_ex_microsoftbot/test_reports
      - run:
         name: Upload coverage report to S3
         command: |
           sudo apt-get install -y awscli
           AWS_ACCESS_KEY_ID=$DOC_SERVICE_AWS_ACCESS_KEY_ID \
           AWS_SECRET_ACCESS_KEY=$DOC_SERVICE_AWS_SECRET_ACCESS_KEY \
           aws s3 cp \
            cover/excoveralls.html \
            s3://pd-doc-service-shrd/pd_ex_microsoftbot/$CIRCLE_BRANCH/coverage.html
      - run:
          name: Post comment to PR
          command: |
            GITHUB_PR_NUMBER=$(echo "$CIRCLE_PULL_REQUEST" | sed "s/.*\/pull\///")
            curl \
              -X POST \
              -d "{\"body\": \"[$CIRCLE_BRANCH/coverage.html](https://doc-service.pd-internal.com/pd_ex_microsoftbot/$CIRCLE_BRANCH/coverage.html)\"}" \
              -H "Authorization: token $GITHUB_PD_CI_ACCESS_TOKEN" \
              "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/issues/${GITHUB_PR_NUMBER}/comments"

workflows:
  version: 2
  test_and_publish:
    jobs:
      - format:
          context:
            - PagerDuty
            - Cloudsmith
            - ECR Production
          filters:
            branches:
              ignore:
                - main
      - compiler_warnings:
          context:
            - PagerDuty
            - Cloudsmith
            - ECR Production
          filters:
            branches:
              ignore:
                - main
      - test:
          context:
            - PagerDuty
            - Cloudsmith
            - ECR Production
          filters:
            branches:
              ignore:
                - main
